### ISSUE TITLE
Broken on python 3.7

### ISSUE THREAD

**Issue by arthuro555** [SpockBotMC/SpockBot-Extra#10]
```
C:\Users\pc\tmp\SpockBot\examples\basic>py example.py
Traceback (most recent call last):
  File "example.py", line 18, in <module>
    from example_plugin import ExamplePlugin
  File "C:\Users\pc\tmp\SpockBot\examples\basic\example_plugin.py", line 17, in <module>
    from spockbot.mcdata import blocks
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Python37\lib\site-packages\spockbot-0.2.0-py3.7.egg\spockbot\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Python37\lib\site-packages\spockbot-0.2.0-py3.7.egg\spockbot\plugins\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1254, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1235, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 594, in spec_from_file_location
  File "C:\Python37\lib\site-packages\spockbot-0.2.0-py3.7.egg\spockbot\plugins\helpers\craft.py", line 87
    yield inv.async.click_slot(ingr_slot)
                  ^
SyntaxError: invalid syntax

```

**Comment by nickelpro** [comment]
This is a problem in Spockbot proper, async is now a reserved keyword so that module would need to be renamed. See https://github.com/SpockBotMC/SpockBot/issues/229
